### PR TITLE
feat: AFK Crab Locations 

### PR DESCRIPTION
**Pull request by csandman**
This PR adds two new sets of tile markers, one for Ammonite Crabs and one for Sand Crabs.  They each provide markers for all of the tiles you can stand to AFK at least 3 of each type of crab, as well as the spawn locations of each crab for each spot.

- [Ammonite Crabs Map](https://runelite.net/tile/show/#W3sicmVnaW9uSWQiOjE1MTYyLCJyZWdpb25YIjoyNywicmVnaW9uWSI6NDMsInoiOjAsImNvbG9yIjoiI0ZGRkZGRjAwIiwibGFiZWwiOiIzIEFtbW9uaXRlIn0seyJyZWdpb25JZCI6MTUxNjIsInJlZ2lvblgiOjMwLCJyZWdpb25ZIjo0MywieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNTE2MiwicmVnaW9uWCI6MzEsInJlZ2lvblkiOjQzLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE1MTYyLCJyZWdpb25YIjozMSwicmVnaW9uWSI6NDQsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTUxNjIsInJlZ2lvblgiOjMwLCJyZWdpb25ZIjo0NCwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNTE2MiwicmVnaW9uWCI6MjcsInJlZ2lvblkiOjQ0LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE1MTYyLCJyZWdpb25YIjoyNywicmVnaW9uWSI6NDUsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTUxNjIsInJlZ2lvblgiOjI2LCJyZWdpb25ZIjo0NSwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNTE2MiwicmVnaW9uWCI6MjYsInJlZ2lvblkiOjQ0LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE1MTYyLCJyZWdpb25YIjoyNSwicmVnaW9uWSI6NDEsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTUxNjIsInJlZ2lvblgiOjI0LCJyZWdpb25ZIjo0MSwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNTE2MiwicmVnaW9uWCI6MjQsInJlZ2lvblkiOjQwLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE1MTYyLCJyZWdpb25YIjoyNSwicmVnaW9uWSI6NDAsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTQ2NTIsInJlZ2lvblgiOjksInJlZ2lvblkiOjM1LCJ6IjowLCJjb2xvciI6IiNGRkZBRkYwMCIsImxhYmVsIjoiMyBBbW1vbml0ZSJ9LHsicmVnaW9uSWQiOjE0NjUyLCJyZWdpb25YIjo4LCJyZWdpb25ZIjozOCwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNDY1MiwicmVnaW9uWCI6OCwicmVnaW9uWSI6MzksInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTQ2NTIsInJlZ2lvblgiOjksInJlZ2lvblkiOjM5LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0NjUyLCJyZWdpb25YIjo5LCJyZWdpb25ZIjozOCwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNDY1MiwicmVnaW9uWCI6MTAsInJlZ2lvblkiOjM2LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0NjUyLCJyZWdpb25YIjoxMSwicmVnaW9uWSI6MzYsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTQ2NTIsInJlZ2lvblgiOjEwLCJyZWdpb25ZIjozNSwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNDY1MiwicmVnaW9uWCI6MTEsInJlZ2lvblkiOjM1LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0NjUyLCJyZWdpb25YIjo5LCJyZWdpb25ZIjozMywieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNDY1MiwicmVnaW9uWCI6MTAsInJlZ2lvblkiOjMzLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0NjUyLCJyZWdpb25YIjo5LCJyZWdpb25ZIjozMiwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNDY1MiwicmVnaW9uWCI6MTAsInJlZ2lvblkiOjMyLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0OTA4LCJyZWdpb25YIjo2LCJyZWdpb25ZIjo2LCJ6IjowLCJjb2xvciI6IiNGRkZBRkYwMCIsImxhYmVsIjoiMyBBbW1vbml0ZSJ9LHsicmVnaW9uSWQiOjE0OTA4LCJyZWdpb25YIjo2LCJyZWdpb25ZIjozLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0OTA4LCJyZWdpb25YIjo2LCJyZWdpb25ZIjo0LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0OTA4LCJyZWdpb25YIjo3LCJyZWdpb25ZIjo0LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0OTA4LCJyZWdpb25YIjo3LCJyZWdpb25ZIjozLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0OTA4LCJyZWdpb25YIjo0LCJyZWdpb25ZIjo5LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0OTA4LCJyZWdpb25YIjo1LCJyZWdpb25ZIjo5LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0OTA4LCJyZWdpb25YIjo0LCJyZWdpb25ZIjoxMCwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNDkwOCwicmVnaW9uWCI6NSwicmVnaW9uWSI6MTAsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTQ5MDgsInJlZ2lvblgiOjMsInJlZ2lvblkiOjYsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTQ5MDgsInJlZ2lvblgiOjQsInJlZ2lvblkiOjYsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTQ5MDgsInJlZ2lvblgiOjMsInJlZ2lvblkiOjUsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTQ5MDgsInJlZ2lvblgiOjQsInJlZ2lvblkiOjUsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTQ5MDgsInJlZ2lvblgiOjIxLCJyZWdpb25ZIjo3LCJ6IjowLCJjb2xvciI6IiNGRkZBRkYwMCIsImxhYmVsIjoiMyBBbW1vbml0ZSJ9LHsicmVnaW9uSWQiOjE0OTA4LCJyZWdpb25YIjoyMCwicmVnaW9uWSI6OSwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNDkwOCwicmVnaW9uWCI6MjEsInJlZ2lvblkiOjksInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTQ5MDgsInJlZ2lvblgiOjIwLCJyZWdpb25ZIjo4LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0OTA4LCJyZWdpb25YIjoyMSwicmVnaW9uWSI6OCwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNDkwOCwicmVnaW9uWCI6MjQsInJlZ2lvblkiOjYsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTQ5MDgsInJlZ2lvblgiOjI1LCJyZWdpb25ZIjo2LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0OTA4LCJyZWdpb25YIjoyNCwicmVnaW9uWSI6NSwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNDkwOCwicmVnaW9uWCI6MjUsInJlZ2lvblkiOjUsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTQ5MDgsInJlZ2lvblgiOjE5LCJyZWdpb25ZIjo1LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjE0OTA4LCJyZWdpb25YIjoyMCwicmVnaW9uWSI6NSwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjoxNDkwOCwicmVnaW9uWCI6MTksInJlZ2lvblkiOjQsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6MTQ5MDgsInJlZ2lvblgiOjIwLCJyZWdpb25ZIjo0LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9XQ)
- [Sand Crabs Map](https://runelite.net/tile/show/#W3sicmVnaW9uSWQiOjY3MTAsInJlZ2lvblgiOjExLCJyZWdpb25ZIjoyMiwieiI6MCwiY29sb3IiOiIjRkZGQUZGMDAiLCJsYWJlbCI6IjMgU2FuZCJ9LHsicmVnaW9uSWQiOjY3MTAsInJlZ2lvblgiOjEwLCJyZWdpb25ZIjoyMiwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2NzEwLCJyZWdpb25YIjoxMSwicmVnaW9uWSI6MjEsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6NjcxMCwicmVnaW9uWCI6MTIsInJlZ2lvblkiOjIxLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjYsInJlZ2lvblgiOjIxLCJyZWdpb25ZIjoxMywieiI6MCwiY29sb3IiOiIjRkZGQUZGMDAiLCJsYWJlbCI6IjMgU2FuZCJ9LHsicmVnaW9uSWQiOjY5NjYsInJlZ2lvblgiOjIwLCJyZWdpb25ZIjoxNCwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY2LCJyZWdpb25YIjoyMiwicmVnaW9uWSI6MTQsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NiwicmVnaW9uWCI6MjIsInJlZ2lvblkiOjEyLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjYsInJlZ2lvblgiOjM3LCJyZWdpb25ZIjoxMiwieiI6MCwiY29sb3IiOiIjRkYwMEM5MzAiLCJsYWJlbCI6IjQgU2FuZCJ9LHsicmVnaW9uSWQiOjY5NjYsInJlZ2lvblgiOjM2LCJyZWdpb25ZIjoxMiwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY2LCJyZWdpb25YIjozOCwicmVnaW9uWSI6MTMsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NiwicmVnaW9uWCI6MzgsInJlZ2lvblkiOjEyLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjYsInJlZ2lvblgiOjM4LCJyZWdpb25ZIjoxMSwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY2LCJyZWdpb25YIjo0OCwicmVnaW9uWSI6MTIsInoiOjAsImNvbG9yIjoiI0ZGRkFGRjAwIiwibGFiZWwiOiIzIFNhbmQifSx7InJlZ2lvbklkIjo2OTY2LCJyZWdpb25YIjo0OCwicmVnaW9uWSI6MTMsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NiwicmVnaW9uWCI6NDcsInJlZ2lvblkiOjEyLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjYsInJlZ2lvblgiOjQ5LCJyZWdpb25ZIjoxMiwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY2LCJyZWdpb25YIjo0NSwicmVnaW9uWSI6NSwieiI6MCwiY29sb3IiOiIjRkZGQUZGMDAiLCJsYWJlbCI6IjMgU2FuZCJ9LHsicmVnaW9uSWQiOjY5NjYsInJlZ2lvblgiOjQ2LCJyZWdpb25ZIjo2LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjYsInJlZ2lvblgiOjQ0LCJyZWdpb25ZIjo1LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjYsInJlZ2lvblgiOjQ1LCJyZWdpb25ZIjo0LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjUsInJlZ2lvblgiOjUyLCJyZWdpb25ZIjoxNSwieiI6MCwiY29sb3IiOiIjRkYwMEM5MzAiLCJsYWJlbCI6IjQgU2FuZCJ9LHsicmVnaW9uSWQiOjY5NjUsInJlZ2lvblgiOjUyLCJyZWdpb25ZIjoxNiwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjo1MywicmVnaW9uWSI6MTYsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6NTEsInJlZ2lvblkiOjE1LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjUsInJlZ2lvblgiOjUyLCJyZWdpb25ZIjoxNCwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjo1OCwicmVnaW9uWSI6MTIsInoiOjAsImNvbG9yIjoiI0ZGMDBDOTMwIiwibGFiZWwiOiI0IFNhbmQifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjo1NywicmVnaW9uWSI6MTIsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6NTgsInJlZ2lvblkiOjExLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjUsInJlZ2lvblgiOjU5LCJyZWdpb25ZIjoxMiwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjo1OSwicmVnaW9uWSI6MTMsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6NDAsInJlZ2lvblkiOjE3LCJ6IjowLCJjb2xvciI6IiNGRkZBRkYwMCIsImxhYmVsIjoiMyBTYW5kIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6NDEsInJlZ2lvblkiOjE3LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjUsInJlZ2lvblgiOjM5LCJyZWdpb25ZIjoxNywieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjo0MCwicmVnaW9uWSI6MTYsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6MjEsInJlZ2lvblkiOjIwLCJ6IjowLCJjb2xvciI6IiNGRjAwQzkzMCIsImxhYmVsIjoiNCBTYW5kIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6MjIsInJlZ2lvblkiOjIxLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjUsInJlZ2lvblgiOjIxLCJyZWdpb25ZIjoyMSwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjoyMCwicmVnaW9uWSI6MjAsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6MjEsInJlZ2lvblkiOjE5LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjUsInJlZ2lvblgiOjIzLCJyZWdpb25ZIjozMywieiI6MCwiY29sb3IiOiIjRkYwMEM5MzAiLCJsYWJlbCI6IjQgU2FuZCJ9LHsicmVnaW9uSWQiOjY5NjUsInJlZ2lvblgiOjI0LCJyZWdpb25ZIjozMywieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjoyMywicmVnaW9uWSI6MzIsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6MjIsInJlZ2lvblkiOjMzLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjUsInJlZ2lvblgiOjIzLCJyZWdpb25ZIjozNCwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjozMCwicmVnaW9uWSI6NDcsInoiOjAsImNvbG9yIjoiI0ZGRkFGRjAwIiwibGFiZWwiOiIzIFNhbmQifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjoyOSwicmVnaW9uWSI6NDcsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6MzEsInJlZ2lvblkiOjQ3LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjUsInJlZ2lvblgiOjMwLCJyZWdpb25ZIjo0OCwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjozNiwicmVnaW9uWSI6NTMsInoiOjAsImNvbG9yIjoiI0ZGMDBDOTMwIiwibGFiZWwiOiI0IFNhbmQifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjozNiwicmVnaW9uWSI6NTIsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6MzUsInJlZ2lvblkiOjUzLCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjUsInJlZ2lvblgiOjM2LCJyZWdpb25ZIjo1NCwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjozNywicmVnaW9uWSI6NTQsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6NTIsInJlZ2lvblkiOjQ2LCJ6IjowLCJjb2xvciI6IiNGRjAwQzkzMCIsImxhYmVsIjoiNCBTYW5kIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6NTMsInJlZ2lvblkiOjQ2LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9LHsicmVnaW9uSWQiOjY5NjUsInJlZ2lvblgiOjUyLCJyZWdpb25ZIjo0NSwieiI6MCwiY29sb3IiOiIjNjRGRjAwMDAifSx7InJlZ2lvbklkIjo2OTY1LCJyZWdpb25YIjo1MSwicmVnaW9uWSI6NDYsInoiOjAsImNvbG9yIjoiIzY0RkYwMDAwIn0seyJyZWdpb25JZCI6Njk2NSwicmVnaW9uWCI6NTIsInJlZ2lvblkiOjQ3LCJ6IjowLCJjb2xvciI6IiM2NEZGMDAwMCJ9XQ)

Each of these sets of tile markers I made for my own purposes, and I think the RuneLite website map may actually be more useful than importing them into the game, but as the site provides both, I think it wouldn't hurt to add them!

### CODE REVIEW

**Comment by jamiegyoung** [comment]
Looks good, did you make the tiles? I cannot see them on the smallxplamp video and I was just wanted to make sure the source for these tiles is correct

**Comment by jamiegyoung** [comment]
I'll merge it nonetheless

**Review by jamiegyoung — APPROVED** [review]

**Comment by csandman** [comment]
Oh yes, I did make the tiles myself! Sorry, I wasn't sure exactly what the source part was for.

**Comment by jamiegyoung** [comment]
All good, I can change it so you or an alias are the source, or I can omit it completely if you would prefer

**Comment by csandman** [comment]
Yeah you can set me as the source if you want, my GitHub I guess?

**Comment by jamiegyoung** [comment]
Can do 👍

**Pull request merged**
